# Generated by Django 4.2.3 on 2023-07-19 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('external_id', models.CharField(max_length=60)),
                ('status', models.CharField(choices=[('1', 'Activo'), ('2', 'Inactivo')], default='1', max_length=10)),
                ('score', models.PositiveBigIntegerField(default=0)),
                ('preapproved_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='loan',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('external_id', models.CharField(max_length=60)),
                ('amount', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('1', 'Pendiente'), ('2', 'Activo'), ('3', 'Rechazado'), ('4', 'Pagado')], default='1', max_length=10)),
                ('contract_version', models.CharField(max_length=30)),
                ('maximum_payment_date', models.DateTimeField()),
                ('taken_at', models.DateTimeField()),
                ('customer_id', models.IntegerField()),
                ('outstanding', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('external_id', models.CharField(max_length=60)),
                ('total_amount', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('1', 'Completado'), ('2', 'Rechazado')], default='1', max_length=10)),
                ('paid_at', models.DateTimeField()),
                ('customer_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='paymentdetail',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('amount', models.IntegerField(default=0)),
                ('loan_id', models.IntegerField()),
                ('payment_id', models.IntegerField()),
            ],
        ),
    ]
