# Generated by Django 4.2.3 on 2023-07-20 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_loan_created_at_alter_loan_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
