# Generated by Django 4.2.3 on 2023-07-20 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_loan_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='contract_version',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='maximum_payment_date',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='taken_at',
        ),
    ]
