# Generated by Django 4.2.3 on 2023-07-21 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_customer_external_id_alter_loan_customer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='customer_id',
        ),
    ]
