# Generated by Django 4.2.3 on 2023-07-21 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_loan_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='external_id',
            field=models.CharField(max_length=60),
        ),
    ]
