# Generated by Django 4.2.3 on 2023-07-21 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_loan_external_id_alter_payment_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='paid_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
